# Deploying instances and security groups
- name: Creating Instances On Nectar
  hosts: localhost
  sudo: yes
  vars_files:
    - variables/instancedetails.yaml
  gather_facts: true
  roles:
   - role: hostPreInstall
   - role: createKeyPair
   - role: createSecurityGroups
   #- role: createVolumes
   - role: createInstances



