---
# Create a volume
- name: Create volume(s) on NecTAR
  os_volume: 
    display_name: '{{ item.vol_name }}'
    size: '{{ item.vol_size }}'
    availability_zone: '{{ availability_zone }}' 
    wait: yes
    timeout: 600
    state: present
  loop: '{{ volumes }}'
  register: os_vol

# Get a list of created volumes
- name: Create a list of volume Ids
  set_fact:
    os_vol_ids: '{{ os_vol_ids|default([]) + [ item.id ] }}'
  loop: '{{ os_vol.results }}'

- debug:
    msg: "Volume {{ os_vol_ids }} has been created."